### ISSUE TITLE
Operation to stop does not match the current operation.

### ISSUE THREAD

**Issue by Tadimsky** [Microsoft/ApplicationInsights-ServiceFabric#64]
I'm getting an error using the Service Remoting telemetry.
It appears that the operation that is being stopped is invalid:

> "message": "AI (Internal): Operation to stop does not match the current operation. Details: Telemetry Id '|1cafaa09-478a33c4492e47c3.a2a37cb4_' does not match current Activity '|1cafaa09-478a33c4492e47c3.a2a37cb4_1.'",

It looks like Application Insights is trying to stop `a2a37cb4_` but it's currently running activity `a2a37cb4_1`. Notice the `1` at the end.

Any ideas why this would be happening?
I'm using 2.1.1-beta1

**Comment by SergeyKanzhelev** [comment]
CC: @lmolkova

**Comment by lmolkova** [comment]
It seems like a known issue: https://github.com/Microsoft/ApplicationInsights-dotnet/issues/693
Which is likely a side effect of https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/723, that reproduces when debugging the app in Visual Studio.

If it is this issue, it should be fixed in Microsoft.ApplicationInsights.DependencyCollector 2.6.0-beta3  and Microsoft.ApplicationInsights.AspNetCore 2.3.0-beta1.

@Tadimsky could you please check versions of DependencyCollector and AspNetCore (and update them). 
Also, do you know if the issue reproduces locally under debug, or in production?

If it reproduces with latest versions, could you please check which if dependency telemetry was reported on the same machine immediately after this message? (unless you have very high-loaded service and this does not make sense?)

Could you please also share some of your telemetries for this operation? 

Please use following Analytics queries
1. requests | union dependencies | where id == "|1cafaa09-478a33c4492e47c3.a2a37cb4_" 
2. requests | union dependencies | where id == "'|1cafaa09-478a33c4492e47c3.a2a37cb4_1." 
3. requests | union dependencies | union traces | where operation_Id == "1cafaa09-478a33c4492e47c3.a2a37cb4" 

Please remove any sensitive information like iKey (or anything else). You can also email this info to me.

**Comment by an4286sc** [comment]
I'm getting this error message too in my current project. But only in production. Not while debugging locally. I'm using this telemetry client methods:
TrackAction
TrackTrace
TrackException

No StartOperation or StopOperation. 

The Application Insights message is: "AI (Internal): Operation to stop does not match the current operation." No further informations.

**Comment by yantang-msft** [comment]
@an4286sc What's the service fabric runtime and AI ServiceFabric version you are on?
Are you using Reliable Service or Actors? Remoting V1 or V2? Did you by any chance use [Shared Process hosting model in Servicefabric](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-hosting-model).
The StartOperation and StopOperation will be called automatically when the request is coming to your service or when you make outgoing request.

Would you be able to share the project that can reproduce the issue? That would be the easiest way for us to trouble shoot.

Other than that, when you see the "AI (Internal): Operation to stop does not match the current operation.", it should give you the TelemetryId, e.g., '|fac5592a-4fd80273c9a61f11.80081fb1_', could you run analytic query like below, this will give us all telemetries happened during the request.
```
requests | union dependencies |
union traces | where operation_Id ==
"fac5592a-4fd80273c9a61f11"
```

**Comment by an4286sc** [comment]
@yantang-msft 
Thanks for your reply. The error occurs in the stateless serivce with remoting v2 and shared process hosting. We are using AI Service Fabric 2.1.1-beta1.

See the query results in the attached file.
[ai_stop_operation_failure.zip](https://github.com/Microsoft/ApplicationInsights-ServiceFabric/files/2008246/ai_stop_operation_failure.zip)

**Comment by yantang-msft** [comment]
@an4286sc I do see discrepancies of the operation ids. And what's the version of Microsoft.ServiceFabric.Services.Remoting? Can you try exclusive process model and see if that solves the problem?
I can try the shared process model later this week and see if I can reproduce the issue. If so, we will keep investigate in how to make it work with shared process model.

**Comment by yantang-msft** [comment]
@Tadimsky @an4286sc I have reproduced this issue and identified the root cause, it's happening for me after I upgraded Microsoft.ApplicationInsights.AspNetCore 2.3.0-beta2. Hopefully you're seeing this error for the same reason.

We are working on the fix, but for some process reason, it will take some time before we can release the fix. A temporary workaround would be downgrade the Microsoft.ApplicationInsights.AspNetCore to 2.2.1.

**Comment by Tadimsky** [comment]
@yantang-msft I am on `2.3.0-beta1`, do you think this version is affected as well?

**Comment by yantang-msft** [comment]
@Tadimsky Yes, I confirm 2.3.0-beta1 is also affected.

**Comment by Tadimsky** [comment]
@yantang-msft is this expected to be fixed in `2.1.1`?
I'm still seeing the issue:

![image](https://user-images.githubusercontent.com/1149244/42060613-45795d34-7adc-11e8-8409-0cd5f1d91f8d.png)

![image](https://user-images.githubusercontent.com/1149244/42060634-5238c104-7adc-11e8-8827-c616acdce09a.png)

**Comment by yantang-msft** [comment]
@Tadimsky Yes, the bug as AI SF side is fixed. Does the huge decrease after 6/25 happened after you upgrade the AI SF package?
It could be somewhere else unrelated to AI SF that is still causing this issue. If you can provide a reproduce, I can definitely take a look and see what's wrong.

**Comment by Tadimsky** [comment]
The huge decrease was due to some increased load we had to process for a few days.

This is total requests into the service:
![image](https://user-images.githubusercontent.com/1149244/42108283-e0b07a14-7b8e-11e8-93e3-b8a6492b521f.png)

We did deploy the fix on 6/27 though - it does seem to be lower, but it's still occurring:
![image](https://user-images.githubusercontent.com/1149244/42108341-02772cec-7b8f-11e8-83cd-c25102db3b12.png)


The project is the same one I shared with you earlier.
Is there something I can try to do to debug this?

**Comment by yantang-msft** [comment]
@Tadimsky can you run the query as you did last time and share the result?
You can try remove the AI SF nuget package and see if this still happens. If so then it's could be some other AI package or if you manually called client.StartOperation but didn't call client.StopOperation properly.
